agent:
  critic_model_arch:
    backend: tensorflow
    class_name: Sequential
    config:
      layers:
      - class_name: ReConcatDense
        config:
          activation: relu
          activity_regularizer: null
          bias_constraint: null
          bias_initializer:
            class_name: Zeros
            config: {}
          bias_regularizer: null
          dtype: float32
          kernel_constraint: null
          kernel_initializer:
            class_name: GlorotUniform
            config:
              seed: null
          kernel_regularizer: null
          name: dense
          trainable: true
          units: 600
          use_bias: true
      - class_name: ReConcatDense
        config:
          activation: relu
          activity_regularizer: null
          bias_constraint: null
          bias_initializer:
            class_name: Zeros
            config: {}
          bias_regularizer: null
          dtype: float32
          kernel_constraint: null
          kernel_initializer:
            class_name: GlorotUniform
            config:
              seed: null
          kernel_regularizer: null
          name: dense_1
          trainable: true
          units: 600
          use_bias: true
      - class_name: Dense
        config:
          activation: relu
          activity_regularizer: null
          bias_constraint: null
          bias_initializer:
            class_name: Zeros
            config: {}
          bias_regularizer: null
          dtype: float32
          kernel_constraint: null
          kernel_initializer:
            class_name: GlorotUniform
            config:
              seed: null
          kernel_regularizer: null
          name: dense_2
          trainable: true
          units: 600
          use_bias: true
      - class_name: Dense
        config:
          activation: relu
          activity_regularizer: null
          bias_constraint: null
          bias_initializer:
            class_name: Zeros
            config: {}
          bias_regularizer: null
          dtype: float32
          kernel_constraint: null
          kernel_initializer:
            class_name: GlorotUniform
            config:
              seed: null
          kernel_regularizer: null
          name: dense_3
          trainable: true
          units: 600
          use_bias: true
      - class_name: Dense
        config:
          activation: tanh
          activity_regularizer: null
          bias_constraint: null
          bias_initializer:
            class_name: Zeros
            config: {}
          bias_regularizer: null
          dtype: float32
          kernel_constraint: null
          kernel_initializer:
            class_name: GlorotUniform
            config:
              seed: null
          kernel_regularizer: null
          name: dense_4
          trainable: true
          units: 1
          use_bias: true
      name: sequential
    keras_version: 2.3.0-tf
