path: ???
n_episodes: 10
gui: False
record: True
exploration: False
resolution:
  - 320
  - 240
overlay: False
n_overlays: 5

hydra:
  run:
    dir: ${path}/../../replays
  sweep:
    dir: ${hydra.run.dir}
    subdir: ""
