path: ???
n_episodes: 1
gui: False
record: True
exploration: False
resolution:
  - 640
  - 480
overlay: False
n_overlays: 5

hydra:
  run:
    dir: ${path}/../../replays
  sweep:
    dir: ${hydra.run.dir}
    subdir: ""
