path: ???
n_episodes: 1
gui: False
record: True
exploration: False
resolution:
  - 640
  - 480
overlay: False
std: 1.0

hydra:
  run:
    dir: ${path}/../../replays_${std}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ""
