type: simple
layers:
  id_0:
    size: 600
    activation: tf.nn.relu
  id_1:
    size: 600
    activation: tf.nn.relu
  id_2:
    size: 600
    activation: tf.nn.relu
  id_3:
    size: 600
    activation: tf.nn.relu
  id_4:
    size: ${simulation.n_joints}
    activation: tf.tanh
