# @package _group_

policy_learning_rate: 1e-3
critic_learning_rate: 1e-3
state_size: 25
action_size: ${simulation.n_joints}
goal_size: ${simulation.n_registers}
n_simulations: ${simulation.n}
target_smoothing_stddev: 0.01
tau: 0.001
exploration_prob: 0.2
