agent:
  policy_model_arch:
    type: simple
    layers:
      id_0:
        size: 200
        activation: tf.nn.relu
      id_1:
        size: 200
        activation: tf.nn.relu
      id_2:
        size: ${simulation.n_joints}
        activation: tf.tanh
